[package]
name = "kakapo-lodge-rates"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
surf = "2.3.2"
tide = "0.16.0"
async-std = { version = "1.12.0", features = ["attributes"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0"
